// Training examples for the intent classifier: English, Tamil script and
// Tamil written in Latin script (code-mixed "Tanglish").
// The farm profile is already known, so only the intent is detected.

export const INTENTS = {
  greeting: [
    'hi', 'hello', 'hey there', 'good morning', 'what can you do', 'help', 'how can you help me',
    'vanakkam', 'hello agrisage', 'enna help pannuva', 'nee enna seiva',
    'வணக்கம்', 'உதவி', 'நீ என்ன செய்வாய்', 'என்ன உதவி செய்ய முடியும்',
  ],
  about: [
    'what is agrisage', 'how does agrisage work', 'how does this system work', 'who made you',
    'is this a chatbot', 'how do you decide', 'does it work offline', 'what technology do you use',
    'agrisage na enna', 'ithu eppadi velai seiyum',
    'அக்ரிசேஜ் என்றால் என்ன', 'இது எப்படி வேலை செய்கிறது', 'இது இணையம் இல்லாமல் வேலை செய்யுமா',
  ],
  should_irrigate: [
    'should i irrigate today', 'do i need to water my crop', 'does my tomato crop need irrigation today',
    'is it time to irrigate', 'when should i irrigate', 'should i water the field now', 'irrigate today or not',
    'how much water should i give today', 'when should i run the pump today', 'is irrigation needed',
    'should i water tomorrow', 'what is the irrigation plan', 'today plan', 'what should i do today',
    'is it a good time to water', 'good day for irrigation',
    'innaiku thanni paichalama', 'thanni vidanuma', 'thanni podalama', 'innaikku irrigation venuma',
    'eppo thanni paichanum', 'motor podalama innaiku', 'neer paichanuma', 'thanni evlo vidanum innaiku',
    'இன்று தண்ணீர் பாய்ச்ச வேண்டுமா', 'இப்போது நீர் பாய்ச்சலாமா', 'தக்காளிக்கு தண்ணீர் விடணுமா',
    'எப்போது தண்ணீர் பாய்ச்ச வேண்டும்', 'இன்றைய திட்டம் என்ன', 'இன்று எவ்வளவு தண்ணீர் கொடுக்க வேண்டும்',
    'நீர் பாய்ச்சல் தேவையா',
  ],
  why_decision: [
    'why', 'why this time', 'why did you decide that', 'explain the decision', 'why not now',
    'why at that time', 'what is the reason', 'why should i wait', 'why skip irrigation', 'explain why',
    'how did you decide this', 'why 9 am',
    'yen', 'yen appadi', 'ethukku', 'karanam enna', 'yen ippo vendam', 'yen andha time',
    'ஏன்', 'ஏன் அப்படி', 'காரணம் என்ன', 'ஏன் இப்போது வேண்டாம்', 'இந்த முடிவு ஏன்', 'ஏன் அந்த நேரம்',
  ],
  what_if: [
    'what if i wait until tomorrow', 'what happens if i skip today', 'what if i irrigate now',
    'what if i do not irrigate', 'compare irrigating now and later', 'what if i delay irrigation',
    'what happens if i water right now', 'what if i wait one day',
    'naalaikku vitta enna aagum', 'wait panna enna aagum', 'ippove thanni vitta enna', 'innaiku vidalanna enna aagum',
    'நாளை வரை காத்திருந்தால் என்ன ஆகும்', 'இப்போதே பாய்ச்சினால் என்ன', 'இன்று பாய்ச்சாவிட்டால் என்ன ஆகும்',
  ],
  farm_status: [
    'what is the soil moisture', 'show farm status', 'how is my farm', 'current sensor readings',
    'soil moisture now', 'how wet is the soil', 'is the soil dry', 'field condition', 'status',
    'mann eerappatham evlo', 'moisture evlo irukku', 'farm epdi irukku', 'mann kaanjirukka',
    'மண் ஈரப்பதம் எவ்வளவு', 'பண்ணை நிலை என்ன', 'மண் காய்ந்திருக்கிறதா', 'சென்சார் அளவுகள்',
  ],
  weather: [
    'will it rain', 'weather forecast', 'is rain expected today', 'how hot will it be today',
    'weather tomorrow', 'rain forecast', 'temperature today', 'humidity today',
    'mazhai varuma', 'rain varuma innaiku', 'weather eppadi', 'veyil evlo',
    'மழை வருமா', 'நாளை வானிலை எப்படி', 'இன்று வெப்பநிலை என்ன', 'மழை முன்னறிவிப்பு',
  ],
  energy_status: [
    'battery status', 'how much solar power now', 'how much energy did the pump use', 'is grid power available',
    'solar generation today', 'battery level', 'energy status', 'is there current now', 'power supply',
    'battery evlo irukku', 'solar evlo varuthu', 'current irukka', 'karent eppo varum', 'power status',
    'பேட்டரி எவ்வளவு இருக்கு', 'சோலார் மின்சாரம் எவ்வளவு', 'கரண்ட் இருக்கா', 'மின்சார நிலை என்ன',
  ],
  pump_control: [
    'turn on the pump', 'start the motor', 'switch on pump', 'run the pump now', 'start irrigation now',
    'turn off the pump', 'stop the motor', 'switch off pump', 'stop irrigation',
    'motor on pannu', 'pump start pannu', 'motor podu', 'motor off pannu', 'motor nirutthu', 'pump stop pannu',
    'மோட்டாரை இயக்கு', 'பம்பை ஆன் செய்', 'மோட்டார் போடு', 'மோட்டாரை நிறுத்து', 'பம்பை ஆஃப் செய்',
  ],
  pump_alert: [
    'is the pump working properly', 'any alerts', 'why did the pump stop', 'pump problem',
    'is there any fault', 'pump health', 'no water coming from pump', 'pump making noise',
    'motor problem irukka', 'yen motor nikkuthu', 'thanni varala', 'alert irukka',
    'மோட்டார் சரியாக வேலை செய்கிறதா', 'ஏதாவது எச்சரிக்கை இருக்கா', 'மோட்டார் ஏன் நின்றது', 'தண்ணீர் வரவில்லை',
  ],
  crop_needs: [
    'how much water does tomato need', 'water requirement of tomato at flowering', 'what does my crop need now',
    'crop water use today', 'tomato flowering care', 'what stage is my crop', 'how much water per day for tomato',
    'tomato ku evlo thanni venum', 'poo pootha samayam enna seiyanum', 'payir enna stage',
    'தக்காளிக்கு எவ்வளவு தண்ணீர் தேவை', 'பூக்கும் பருவத்தில் என்ன கவனிக்க வேண்டும்', 'பயிர் எந்த பருவத்தில் உள்ளது',
    'பூக்கும் பருவத்தில் தக்காளிக்கு எவ்வளவு தண்ணீர் தேவை', 'ஒரு நாளைக்கு தக்காளிக்கு எவ்வளவு தண்ணீர்',
  ],
  disease_help: [
    'leaves have brown spots', 'brown spots with rings on leaves', 'leaves are curling', 'yellow leaves',
    'plant is wilting', 'black rot at the bottom of the fruit', 'white fungus under the leaves', 'my plant has a disease',
    'leaves turning yellow and curling', 'whole plant suddenly wilted', 'what disease is this', 'pest attack on tomato',
    'ilai la pulli irukku', 'ilai surundu pochu', 'ilai manjal aaguthu', 'chedi vaadi pochu', 'pazham adiyila karuppu',
    'இலையில் பழுப்பு புள்ளிகள் உள்ளன', 'இலைகள் சுருண்டு போகின்றன', 'இலைகள் மஞ்சளாகின்றன', 'செடி வாடுகிறது',
    'பழத்தின் அடியில் கருப்பு அழுகல்', 'இது என்ன நோய்',
  ],
  impact: [
    'how much water did we save', 'what is the impact', 'savings this season', 'compare with normal irrigation',
    'how much energy saved', 'co2 reduction', 'show season results', 'benefit compared to farmer practice',
    'how much water does agrisage save', 'water savings per hectare', 'how much can a farmer save', 'season impact numbers',
    'evlo thanni save aachu', 'savings evlo', 'labam enna',
    'எவ்வளவு தண்ணீர் சேமித்தோம்', 'எவ்வளவு மின்சாரம் மிச்சம்', 'இதனால் என்ன பயன்', 'எவ்வளவு தண்ணீர் சேமிக்கிறது',
  ],
};

// Held-out questions with expected intents (not used for training).
export const TEST_SET = [
  ['Do I have to irrigate the tomatoes today?', 'should_irrigate'],
  ['Is today a good day to water?', 'should_irrigate'],
  ['inniku thanni pachalama?', 'should_irrigate'],
  ['இன்னைக்கு தண்ணீர் பாய்ச்சலாமா?', 'should_irrigate'],
  ['why 9 o clock?', 'why_decision'],
  ['Why are you telling me to skip?', 'why_decision'],
  ['ஏன் இந்த நேரம்?', 'why_decision'],
  ['what happens if I wait till tomorrow morning', 'what_if'],
  ['naalai varai wait pannalama, enna aagum?', 'what_if'],
  ['இப்பவே தண்ணீர் விட்டால் என்ன ஆகும்?', 'what_if'],
  ['How dry is my soil right now?', 'farm_status'],
  ['moisture level evlo?', 'farm_status'],
  ['மண்ணில் ஈரம் எவ்வளவு உள்ளது?', 'farm_status'],
  ['Is it going to rain tonight?', 'weather'],
  ['mazhai varumaa naalaikku', 'weather'],
  ['இன்று மழை பெய்யுமா?', 'weather'],
  ['How charged is the battery?', 'energy_status'],
  ['solar power evlo produce aaguthu', 'energy_status'],
  ['சோலார் எவ்வளவு உற்பத்தி செய்கிறது?', 'energy_status'],
  ['Please switch the motor on', 'pump_control'],
  ['motor off pannunga', 'pump_control'],
  ['மோட்டாரை ஆன் பண்ணு', 'pump_control'],
  ['The pump is running but no water is coming', 'pump_alert'],
  ['ஏதாவது பிரச்சனை அலர்ட் இருக்கா?', 'pump_alert'],
  ['How much water does a flowering tomato need per day?', 'crop_needs'],
  ['தக்காளி பூக்கும் போது எவ்வளவு தண்ணீர் வேண்டும்?', 'crop_needs'],
  ['The lower leaves have dark spots with rings', 'disease_help'],
  ['ilaigal surungi manjal aagudhu', 'disease_help'],
  ['இலையின் கீழே வெள்ளை பூஞ்சை உள்ளது', 'disease_help'],
  ['How much water and energy does AgriSage save in a season?', 'impact'],
  ['vanakkam, neenga yaaru?', 'greeting'],
  ['How does AgriSage decide when to irrigate?', 'about'],
  // Second batch, added after tuning and never used for tuning.
  ['Do the plants need water now?', 'should_irrigate'],
  ['thanni paichalaama illa venaama?', 'should_irrigate'],
  ['why did you choose that time slot', 'why_decision'],
  ['Will there be rain this week?', 'weather'],
  ['வெயில் அதிகமா இருக்குமா?', 'weather'],
  ['What is the battery percentage?', 'energy_status'],
  ['மோட்டாரை நிறுத்துங்கள்', 'pump_control'],
  ['Stop the pump please', 'pump_control'],
  ['leaves look burnt with concentric circles', 'disease_help'],
  ['செடிகள் திடீரென வாடி விட்டன', 'disease_help'],
  ['How much CO2 does this reduce?', 'impact'],
  ['What growth stage is the crop in?', 'crop_needs'],
  ['If I water at night instead, what changes?', 'what_if'],
  ['is the field too dry', 'farm_status'],
];

// Out-of-domain questions that must fall back to "other".
export const OOD_SET = ['what is the capital of france', 'tell me a joke', 'asdf qwer', 'who won the cricket match yesterday', 'write a poem about love'];
